//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.desc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imf.oplexecutor.fims.desc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BmContentDescription_QNAME = new QName("http://description.fims.tv", "bmContentDescription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imf.oplexecutor.fims.desc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganisationDetailsType }
     * 
     */
    public OrganisationDetailsType createOrganisationDetailsType() {
        return new OrganisationDetailsType();
    }

    /**
     * Create an instance of {@link CoverageType }
     * 
     */
    public CoverageType createCoverageType() {
        return new CoverageType();
    }

    /**
     * Create an instance of {@link CoverageType.Spatial }
     * 
     */
    public CoverageType.Spatial createCoverageTypeSpatial() {
        return new CoverageType.Spatial();
    }

    /**
     * Create an instance of {@link RightsType }
     * 
     */
    public RightsType createRightsType() {
        return new RightsType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link RegionType }
     * 
     */
    public RegionType createRegionType() {
        return new RegionType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ContactDetailsType }
     * 
     */
    public ContactDetailsType createContactDetailsType() {
        return new ContactDetailsType();
    }

    /**
     * Create an instance of {@link BmContentDescriptionType }
     * 
     */
    public BmContentDescriptionType createBmContentDescriptionType() {
        return new BmContentDescriptionType();
    }

    /**
     * Create an instance of {@link AudienceType }
     * 
     */
    public AudienceType createAudienceType() {
        return new AudienceType();
    }

    /**
     * Create an instance of {@link PartType }
     * 
     */
    public PartType createPartType() {
        return new PartType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link TextElementType }
     * 
     */
    public TextElementType createTextElementType() {
        return new TextElementType();
    }

    /**
     * Create an instance of {@link DetailsType }
     * 
     */
    public DetailsType createDetailsType() {
        return new DetailsType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link AlternativeTitleType }
     * 
     */
    public AlternativeTitleType createAlternativeTitleType() {
        return new AlternativeTitleType();
    }

    /**
     * Create an instance of {@link CompoundNameType }
     * 
     */
    public CompoundNameType createCompoundNameType() {
        return new CompoundNameType();
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link OrganisationDetailsType.OrganisationDepartment }
     * 
     */
    public OrganisationDetailsType.OrganisationDepartment createOrganisationDetailsTypeOrganisationDepartment() {
        return new OrganisationDetailsType.OrganisationDepartment();
    }

    /**
     * Create an instance of {@link OrganisationDetailsType.RelatedInformationLink }
     * 
     */
    public OrganisationDetailsType.RelatedInformationLink createOrganisationDetailsTypeRelatedInformationLink() {
        return new OrganisationDetailsType.RelatedInformationLink();
    }

    /**
     * Create an instance of {@link CoverageType.Temporal }
     * 
     */
    public CoverageType.Temporal createCoverageTypeTemporal() {
        return new CoverageType.Temporal();
    }

    /**
     * Create an instance of {@link CoverageType.Spatial.LocationName }
     * 
     */
    public CoverageType.Spatial.LocationName createCoverageTypeSpatialLocationName() {
        return new CoverageType.Spatial.LocationName();
    }

    /**
     * Create an instance of {@link CoverageType.Spatial.Coordinates }
     * 
     */
    public CoverageType.Spatial.Coordinates createCoverageTypeSpatialCoordinates() {
        return new CoverageType.Spatial.Coordinates();
    }

    /**
     * Create an instance of {@link RightsType.ProcessingRestrictionFlag }
     * 
     */
    public RightsType.ProcessingRestrictionFlag createRightsTypeProcessingRestrictionFlag() {
        return new RightsType.ProcessingRestrictionFlag();
    }

    /**
     * Create an instance of {@link TypeType.Genre }
     * 
     */
    public TypeType.Genre createTypeTypeGenre() {
        return new TypeType.Genre();
    }

    /**
     * Create an instance of {@link TypeType.ObjectType }
     * 
     */
    public TypeType.ObjectType createTypeTypeObjectType() {
        return new TypeType.ObjectType();
    }

    /**
     * Create an instance of {@link RegionType.Country }
     * 
     */
    public RegionType.Country createRegionTypeCountry() {
        return new RegionType.Country();
    }

    /**
     * Create an instance of {@link RegionType.CountryRegion }
     * 
     */
    public RegionType.CountryRegion createRegionTypeCountryRegion() {
        return new RegionType.CountryRegion();
    }

    /**
     * Create an instance of {@link EntityType.Role }
     * 
     */
    public EntityType.Role createEntityTypeRole() {
        return new EntityType.Role();
    }

    /**
     * Create an instance of {@link DateType.Created }
     * 
     */
    public DateType.Created createDateTypeCreated() {
        return new DateType.Created();
    }

    /**
     * Create an instance of {@link DateType.Modified }
     * 
     */
    public DateType.Modified createDateTypeModified() {
        return new DateType.Modified();
    }

    /**
     * Create an instance of {@link DateType.Issued }
     * 
     */
    public DateType.Issued createDateTypeIssued() {
        return new DateType.Issued();
    }

    /**
     * Create an instance of {@link DateType.Digitised }
     * 
     */
    public DateType.Digitised createDateTypeDigitised() {
        return new DateType.Digitised();
    }

    /**
     * Create an instance of {@link DateType.Released }
     * 
     */
    public DateType.Released createDateTypeReleased() {
        return new DateType.Released();
    }

    /**
     * Create an instance of {@link DateType.Encoded }
     * 
     */
    public DateType.Encoded createDateTypeEncoded() {
        return new DateType.Encoded();
    }

    /**
     * Create an instance of {@link DateType.Copyrighted }
     * 
     */
    public DateType.Copyrighted createDateTypeCopyrighted() {
        return new DateType.Copyrighted();
    }

    /**
     * Create an instance of {@link DateType.Alternative }
     * 
     */
    public DateType.Alternative createDateTypeAlternative() {
        return new DateType.Alternative();
    }

    /**
     * Create an instance of {@link AddressType.Country }
     * 
     */
    public AddressType.Country createAddressTypeCountry() {
        return new AddressType.Country();
    }

    /**
     * Create an instance of {@link ContactDetailsType.RelatedInformationLink }
     * 
     */
    public ContactDetailsType.RelatedInformationLink createContactDetailsTypeRelatedInformationLink() {
        return new ContactDetailsType.RelatedInformationLink();
    }

    /**
     * Create an instance of {@link BmContentDescriptionType.Version }
     * 
     */
    public BmContentDescriptionType.Version createBmContentDescriptionTypeVersion() {
        return new BmContentDescriptionType.Version();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BmContentDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://description.fims.tv", name = "bmContentDescription")
    public JAXBElement<BmContentDescriptionType> createBmContentDescription(BmContentDescriptionType value) {
        return new JAXBElement<BmContentDescriptionType>(_BmContentDescription_QNAME, BmContentDescriptionType.class, null, value);
    }

}
