//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.tfms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imf.oplexecutor.fims.tfms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransformNotification_QNAME = new QName("http://transformmedia.fims.tv", "transformNotification");
    private final static QName _TransformFaultNotification_QNAME = new QName("http://transformmedia.fims.tv", "transformFaultNotification");
    private final static QName _TransformAck_QNAME = new QName("http://transformmedia.fims.tv", "transformAck");
    private final static QName _TransformFault_QNAME = new QName("http://transformmedia.fims.tv", "transformFault");
    private final static QName _TransformRequest_QNAME = new QName("http://transformmedia.fims.tv", "transformRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imf.oplexecutor.fims.tfms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransformJobType }
     * 
     */
    public TransformJobType createTransformJobType() {
        return new TransformJobType();
    }

    /**
     * Create an instance of {@link TransformNotificationType }
     * 
     */
    public TransformNotificationType createTransformNotificationType() {
        return new TransformNotificationType();
    }

    /**
     * Create an instance of {@link TransformResponseType }
     * 
     */
    public TransformResponseType createTransformResponseType() {
        return new TransformResponseType();
    }

    /**
     * Create an instance of {@link TransformFaultType }
     * 
     */
    public TransformFaultType createTransformFaultType() {
        return new TransformFaultType();
    }

    /**
     * Create an instance of {@link TransformFaultNotificationType }
     * 
     */
    public TransformFaultNotificationType createTransformFaultNotificationType() {
        return new TransformFaultNotificationType();
    }

    /**
     * Create an instance of {@link TransformRequestType }
     * 
     */
    public TransformRequestType createTransformRequestType() {
        return new TransformRequestType();
    }

    /**
     * Create an instance of {@link TransformProfileType }
     * 
     */
    public TransformProfileType createTransformProfileType() {
        return new TransformProfileType();
    }

    /**
     * Create an instance of {@link TransformJobType.Profiles }
     * 
     */
    public TransformJobType.Profiles createTransformJobTypeProfiles() {
        return new TransformJobType.Profiles();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://transformmedia.fims.tv", name = "transformNotification")
    public JAXBElement<TransformNotificationType> createTransformNotification(TransformNotificationType value) {
        return new JAXBElement<TransformNotificationType>(_TransformNotification_QNAME, TransformNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformFaultNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://transformmedia.fims.tv", name = "transformFaultNotification")
    public JAXBElement<TransformFaultNotificationType> createTransformFaultNotification(TransformFaultNotificationType value) {
        return new JAXBElement<TransformFaultNotificationType>(_TransformFaultNotification_QNAME, TransformFaultNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://transformmedia.fims.tv", name = "transformAck")
    public JAXBElement<TransformResponseType> createTransformAck(TransformResponseType value) {
        return new JAXBElement<TransformResponseType>(_TransformAck_QNAME, TransformResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://transformmedia.fims.tv", name = "transformFault")
    public JAXBElement<TransformFaultType> createTransformFault(TransformFaultType value) {
        return new JAXBElement<TransformFaultType>(_TransformFault_QNAME, TransformFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://transformmedia.fims.tv", name = "transformRequest")
    public JAXBElement<TransformRequestType> createTransformRequest(TransformRequestType value) {
        return new JAXBElement<TransformRequestType>(_TransformRequest_QNAME, TransformRequestType.class, null, value);
    }

}
