//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.tfms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Modified In Version: 1_1_0
 * 
 * <p>Java class for TransformFaultNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransformFaultNotificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="transformJob" type="{http://transformmedia.fims.tv}TransformJobType"/>
 *         &lt;/sequence>
 *         &lt;element name="fault" type="{http://transformmedia.fims.tv}TransformFaultType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://base.fims.tv}CurrentVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransformFaultNotificationType", propOrder = {
    "transformJob",
    "fault"
})
public class TransformFaultNotificationType {

    @XmlElement(required = true)
    protected TransformJobType transformJob;
    @XmlElement(required = true)
    protected TransformFaultType fault;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the transformJob property.
     * 
     * @return
     *     possible object is
     *     {@link TransformJobType }
     *     
     */
    public TransformJobType getTransformJob() {
        return transformJob;
    }

    /**
     * Sets the value of the transformJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformJobType }
     *     
     */
    public void setTransformJob(TransformJobType value) {
        this.transformJob = value;
    }

    /**
     * Gets the value of the fault property.
     * 
     * @return
     *     possible object is
     *     {@link TransformFaultType }
     *     
     */
    public TransformFaultType getFault() {
        return fault;
    }

    /**
     * Sets the value of the fault property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformFaultType }
     *     
     */
    public void setFault(TransformFaultType value) {
        this.fault = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
