//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.tfms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.imf.oplexecutor.fims.bms.JobType;


/**
 * <p>Java class for TransformJobType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransformJobType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://base.fims.tv}JobType">
 *       &lt;sequence>
 *         &lt;element name="profiles" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transformProfile" type="{http://transformmedia.fims.tv}TransformProfileType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransformJobType", propOrder = {
    "profiles"
})
public class TransformJobType
    extends JobType
{

    protected TransformJobType.Profiles profiles;

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link TransformJobType.Profiles }
     *     
     */
    public TransformJobType.Profiles getProfiles() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformJobType.Profiles }
     *     
     */
    public void setProfiles(TransformJobType.Profiles value) {
        this.profiles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transformProfile" type="{http://transformmedia.fims.tv}TransformProfileType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transformProfile"
    })
    public static class Profiles {

        @XmlElement(required = true)
        protected List<TransformProfileType> transformProfile;

        /**
         * Gets the value of the transformProfile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transformProfile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransformProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TransformProfileType }
         * 
         * 
         */
        public List<TransformProfileType> getTransformProfile() {
            if (transformProfile == null) {
                transformProfile = new ArrayList<TransformProfileType>();
            }
            return this.transformProfile;
        }

    }

}
