//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.mdcf.q;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.imf.oplexecutor.fims.mdcf.b.USNs;


/**
 * <p>Java class for getNamespacesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getNamespacesResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.smpte-ra.org/schemas/st2071/2015/identity}USNs"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNamespacesResponse", propOrder = {
    "usNs"
})
public class GetNamespacesResponse {

    @XmlElement(name = "USNs", namespace = "http://www.smpte-ra.org/schemas/st2071/2015/identity", required = true)
    protected USNs usNs;

    /**
     * Gets the value of the usNs property.
     * 
     * @return
     *     possible object is
     *     {@link USNs }
     *     
     */
    public USNs getUSNs() {
        return usNs;
    }

    /**
     * Sets the value of the usNs property.
     * 
     * @param value
     *     allowed object is
     *     {@link USNs }
     *     
     */
    public void setUSNs(USNs value) {
        this.usNs = value;
    }

}
