//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.tim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * Element(s) supported.
 * 
 * <p>Java class for DurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="timecode" type="{http://baseTime.fims.tv}TimecodeDuration"/>
 *         &lt;element name="normalPlayTime" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *         &lt;element name="editUnitNumber" type="{http://baseTime.fims.tv}EditUnitNumberType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DurationType", propOrder = {
    "timecode",
    "normalPlayTime",
    "editUnitNumber"
})
public class DurationType {

    protected String timecode;
    protected Duration normalPlayTime;
    protected EditUnitNumberType editUnitNumber;

    /**
     * Gets the value of the timecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimecode() {
        return timecode;
    }

    /**
     * Sets the value of the timecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimecode(String value) {
        this.timecode = value;
    }

    /**
     * Gets the value of the normalPlayTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getNormalPlayTime() {
        return normalPlayTime;
    }

    /**
     * Sets the value of the normalPlayTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setNormalPlayTime(Duration value) {
        this.normalPlayTime = value;
    }

    /**
     * Gets the value of the editUnitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link EditUnitNumberType }
     *     
     */
    public EditUnitNumberType getEditUnitNumber() {
        return editUnitNumber;
    }

    /**
     * Sets the value of the editUnitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditUnitNumberType }
     *     
     */
    public void setEditUnitNumber(EditUnitNumberType value) {
        this.editUnitNumber = value;
    }

}
