//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.imf.oplexecutor.fims.tim.DurationType;
import org.imf.oplexecutor.fims.tim.TimeType;


/**
 * <p>Java class for BasePartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasePartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceContentIDRef" type="{http://base.fims.tv}UID"/>
 *         &lt;element name="start" type="{http://baseTime.fims.tv}TimeType" minOccurs="0"/>
 *         &lt;element name="duration" type="{http://baseTime.fims.tv}DurationType" minOccurs="0"/>
 *         &lt;element name="ExtensionGroup" type="{http://base.fims.tv}ExtensionGroup" minOccurs="0"/>
 *         &lt;element name="ExtensionAttributes" type="{http://base.fims.tv}ExtensionAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasePartType", propOrder = {
    "sourceContentIDRef",
    "start",
    "duration",
    "extensionGroup",
    "extensionAttributes"
})
@XmlSeeAlso({
    OrderedPartType.class,
    ContentPartAtomType.class
})
public class BasePartType {

    @XmlElement(required = true)
    protected String sourceContentIDRef;
    protected TimeType start;
    protected DurationType duration;
    @XmlElement(name = "ExtensionGroup")
    protected ExtensionGroup extensionGroup;
    @XmlElement(name = "ExtensionAttributes")
    protected ExtensionAttributes extensionAttributes;

    /**
     * Gets the value of the sourceContentIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceContentIDRef() {
        return sourceContentIDRef;
    }

    /**
     * Sets the value of the sourceContentIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceContentIDRef(String value) {
        this.sourceContentIDRef = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link TimeType }
     *     
     */
    public TimeType getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeType }
     *     
     */
    public void setStart(TimeType value) {
        this.start = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationType }
     *     
     */
    public DurationType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationType }
     *     
     */
    public void setDuration(DurationType value) {
        this.duration = value;
    }

    /**
     * Gets the value of the extensionGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionGroup }
     *     
     */
    public ExtensionGroup getExtensionGroup() {
        return extensionGroup;
    }

    /**
     * Sets the value of the extensionGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionGroup }
     *     
     */
    public void setExtensionGroup(ExtensionGroup value) {
        this.extensionGroup = value;
    }

    /**
     * Gets the value of the extensionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionAttributes }
     *     
     */
    public ExtensionAttributes getExtensionAttributes() {
        return extensionAttributes;
    }

    /**
     * Sets the value of the extensionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionAttributes }
     *     
     */
    public void setExtensionAttributes(ExtensionAttributes value) {
        this.extensionAttributes = value;
    }

}
