//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BMContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BMContentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://base.fims.tv}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="bmContentFormats" type="{http://base.fims.tv}BMContentFormatsType" minOccurs="0"/>
 *         &lt;element name="qaReportReferences" type="{http://base.fims.tv}QAReportReferencesType" minOccurs="0"/>
 *         &lt;element name="descriptions" type="{http://base.fims.tv}DescriptionsType" minOccurs="0"/>
 *         &lt;element name="status" type="{http://base.fims.tv}BMContentStatusType" minOccurs="0"/>
 *         &lt;element name="timelines" type="{http://base.fims.tv}TimelinesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BMContentType", propOrder = {
    "bmContentFormats",
    "qaReportReferences",
    "descriptions",
    "status",
    "timelines"
})
public class BMContentType
    extends ResourceType
{

    protected BMContentFormatsType bmContentFormats;
    protected QAReportReferencesType qaReportReferences;
    protected DescriptionsType descriptions;
    protected BMContentStatusType status;
    protected TimelinesType timelines;

    /**
     * Gets the value of the bmContentFormats property.
     * 
     * @return
     *     possible object is
     *     {@link BMContentFormatsType }
     *     
     */
    public BMContentFormatsType getBmContentFormats() {
        return bmContentFormats;
    }

    /**
     * Sets the value of the bmContentFormats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BMContentFormatsType }
     *     
     */
    public void setBmContentFormats(BMContentFormatsType value) {
        this.bmContentFormats = value;
    }

    /**
     * Gets the value of the qaReportReferences property.
     * 
     * @return
     *     possible object is
     *     {@link QAReportReferencesType }
     *     
     */
    public QAReportReferencesType getQaReportReferences() {
        return qaReportReferences;
    }

    /**
     * Sets the value of the qaReportReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link QAReportReferencesType }
     *     
     */
    public void setQaReportReferences(QAReportReferencesType value) {
        this.qaReportReferences = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionsType }
     *     
     */
    public DescriptionsType getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionsType }
     *     
     */
    public void setDescriptions(DescriptionsType value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BMContentStatusType }
     *     
     */
    public BMContentStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BMContentStatusType }
     *     
     */
    public void setStatus(BMContentStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the timelines property.
     * 
     * @return
     *     possible object is
     *     {@link TimelinesType }
     *     
     */
    public TimelinesType getTimelines() {
        return timelines;
    }

    /**
     * Sets the value of the timelines property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimelinesType }
     *     
     */
    public void setTimelines(TimelinesType value) {
        this.timelines = value;
    }

}
