//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BMStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BMStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="new"/>
 *     &lt;enumeration value="online"/>
 *     &lt;enumeration value="offline"/>
 *     &lt;enumeration value="removed"/>
 *     &lt;enumeration value="purged"/>
 *     &lt;enumeration value="invalid"/>
 *     &lt;enumeration value="processing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BMStatusType")
@XmlEnum
public enum BMStatusType {


    /**
     * 
     *             This value indicates the current status of the instance resource is "new".
     *           
     * 
     */
    @XmlEnumValue("new")
    NEW("new"),

    /**
     * 
     *             This value indicates the current status of the instance resource is "online" and active.
     *           
     * 
     */
    @XmlEnumValue("online")
    ONLINE("online"),

    /**
     * 
     *             This value indicates the current status of the instance resource is "offline" and inactive.
     *           
     * 
     */
    @XmlEnumValue("offline")
    OFFLINE("offline"),

    /**
     * 
     *             This value indicates the current status of the instance resource is "removed" and marked for purge.
     *           
     * 
     */
    @XmlEnumValue("removed")
    REMOVED("removed"),

    /**
     * 
     *             This value indicates the current status of the instance resource has been "purged" and is no longer accessible.
     *           
     * 
     */
    @XmlEnumValue("purged")
    PURGED("purged"),

    /**
     * 
     *             This value indicates the current status of the instance resource is "invalid" and may be corrupt.
     *           
     * 
     */
    @XmlEnumValue("invalid")
    INVALID("invalid"),

    /**
     * 
     *             This value indicates the current status of the instance resource is "processing" and currently changing state.
     *           
     * 
     */
    @XmlEnumValue("processing")
    PROCESSING("processing");
    private final String value;

    BMStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BMStatusType fromValue(String v) {
        for (BMStatusType c: BMStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
