//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Introduced In Version: 1_1_0
 * 
 * <p>Java class for ContentEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://base.fims.tv}EventPayloadType">
 *       &lt;sequence>
 *         &lt;element name="targetResourceReference" type="{http://base.fims.tv}ResourceReferenceType" minOccurs="0"/>
 *         &lt;element name="ExtensionGroup" type="{http://base.fims.tv}ExtensionGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentEventType", propOrder = {
    "targetResourceReference",
    "extensionGroup"
})
@XmlSeeAlso({
    ContentStatusEventType.class,
    ContentCustomEventType.class
})
public abstract class ContentEventType
    extends EventPayloadType
{

    protected ResourceReferenceType targetResourceReference;
    @XmlElement(name = "ExtensionGroup")
    protected ExtensionGroup extensionGroup;

    /**
     * Gets the value of the targetResourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceReferenceType }
     *     
     */
    public ResourceReferenceType getTargetResourceReference() {
        return targetResourceReference;
    }

    /**
     * Sets the value of the targetResourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceReferenceType }
     *     
     */
    public void setTargetResourceReference(ResourceReferenceType value) {
        this.targetResourceReference = value;
    }

    /**
     * Gets the value of the extensionGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionGroup }
     *     
     */
    public ExtensionGroup getExtensionGroup() {
        return extensionGroup;
    }

    /**
     * Sets the value of the extensionGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionGroup }
     *     
     */
    public void setExtensionGroup(ExtensionGroup value) {
        this.extensionGroup = value;
    }

}
