//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Introduced In Version: 1_1_0
 * 
 * <p>Java class for ContentCustomEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentCustomEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://base.fims.tv}ContentEventType">
 *       &lt;sequence>
 *         &lt;element name="templateID" type="{http://base.fims.tv}ResourceIDType" minOccurs="0"/>
 *         &lt;element name="customEventTemplate" type="{http://base.fims.tv}CustomEventTemplateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentCustomEventType", propOrder = {
    "templateID",
    "customEventTemplate"
})
public class ContentCustomEventType
    extends ContentEventType
{

    protected String templateID;
    protected CustomEventTemplateType customEventTemplate;

    /**
     * Gets the value of the templateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateID() {
        return templateID;
    }

    /**
     * Sets the value of the templateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateID(String value) {
        this.templateID = value;
    }

    /**
     * Gets the value of the customEventTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link CustomEventTemplateType }
     *     
     */
    public CustomEventTemplateType getCustomEventTemplate() {
        return customEventTemplate;
    }

    /**
     * Sets the value of the customEventTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomEventTemplateType }
     *     
     */
    public void setCustomEventTemplate(CustomEventTemplateType value) {
        this.customEventTemplate = value;
    }

}
