//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventSubType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventSubType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="systemException"/>
 *     &lt;enumeration value="systemPerformance"/>
 *     &lt;enumeration value="created"/>
 *     &lt;enumeration value="removed"/>
 *     &lt;enumeration value="purged"/>
 *     &lt;enumeration value="relocated"/>
 *     &lt;enumeration value="newFormatAvailable"/>
 *     &lt;enumeration value="copied"/>
 *     &lt;enumeration value="qced"/>
 *     &lt;enumeration value="modified"/>
 *     &lt;enumeration value="custom"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventSubType")
@XmlEnum
public enum EventSubType {


    /**
     * 
     *             Indicates a "system exception" occurred.
     *           
     * 
     */
    @XmlEnumValue("systemException")
    SYSTEM_EXCEPTION("systemException"),

    /**
     * 
     *             Indicates a "system performance" event type.
     *           
     * 
     */
    @XmlEnumValue("systemPerformance")
    SYSTEM_PERFORMANCE("systemPerformance"),

    /**
     * 
     *             Indicates a "created" event.
     *           
     * 
     */
    @XmlEnumValue("created")
    CREATED("created"),

    /**
     * 
     *             Indicates a "removed" and ready to be purged event.
     *           
     * 
     */
    @XmlEnumValue("removed")
    REMOVED("removed"),

    /**
     * 
     *             Indicates a "purged" and is no longer available event.
     *           
     * 
     */
    @XmlEnumValue("purged")
    PURGED("purged"),

    /**
     * 
     *             Indicates a "relocated" event.
     *           
     * 
     */
    @XmlEnumValue("relocated")
    RELOCATED("relocated"),

    /**
     * 
     *             Indicates a "new format available" event.
     *           
     * 
     */
    @XmlEnumValue("newFormatAvailable")
    NEW_FORMAT_AVAILABLE("newFormatAvailable"),

    /**
     * 
     *             Indicates a "copied" event.
     *           
     * 
     */
    @XmlEnumValue("copied")
    COPIED("copied"),

    /**
     * 
     *             Indicates a "qced" event.
     *           
     * 
     */
    @XmlEnumValue("qced")
    QCED("qced"),

    /**
     * 
     *             Indicates a "modified" event.
     *           
     * 
     */
    @XmlEnumValue("modified")
    MODIFIED("modified"),

    /**
     * 
     *             Indicates a "custom" event.
     *           
     * 
     */
    @XmlEnumValue("custom")
    CUSTOM("custom");
    private final String value;

    EventSubType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventSubType fromValue(String v) {
        for (EventSubType c: EventSubType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
