//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventClassificationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventClassificationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="warning"/>
 *     &lt;enumeration value="information"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventClassificationType")
@XmlEnum
public enum EventClassificationType {


    /**
     * 
     *             Indicates the "error" classification level.
     *           
     * 
     */
    @XmlEnumValue("error")
    ERROR("error"),

    /**
     * 
     *             Indicates the "warning" classification level.
     *           
     * 
     */
    @XmlEnumValue("warning")
    WARNING("warning"),

    /**
     * 
     *             Indicates the "information" classification level.
     *           
     * 
     */
    @XmlEnumValue("information")
    INFORMATION("information");
    private final String value;

    EventClassificationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventClassificationType fromValue(String v) {
        for (EventClassificationType c: EventClassificationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
