//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriorityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PriorityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="low"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="high"/>
 *     &lt;enumeration value="urgent"/>
 *     &lt;enumeration value="immediate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PriorityType")
@XmlEnum
public enum PriorityType {


    /**
     * 
     *             Job initially allocated to the end of the queue.
     *           
     * 
     */
    @XmlEnumValue("low")
    LOW("low"),

    /**
     * 
     *             Job initially allocated to be executed before any low priority jobs but after any existing medium priority jobs.
     *           
     * 
     */
    @XmlEnumValue("medium")
    MEDIUM("medium"),

    /**
     * 
     *             Job initially allocated before any medium and low priority jobs but after existing high priority jobs.
     *           
     * 
     */
    @XmlEnumValue("high")
    HIGH("high"),

    /**
     * 
     *             Job initially allocated to be executed before any high, medium and low priority jobs but after existing urgent jobs.
     *           
     * 
     */
    @XmlEnumValue("urgent")
    URGENT("urgent"),

    /**
     * 
     *             Job should be executed as soon as the request is received.
     *           
     * 
     */
    @XmlEnumValue("immediate")
    IMMEDIATE("immediate");
    private final String value;

    PriorityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PriorityType fromValue(String v) {
        for (PriorityType c: PriorityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
