//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryParameterOperatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QueryParameterOperatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="equal"/>
 *     &lt;enumeration value="notEqual"/>
 *     &lt;enumeration value="greater"/>
 *     &lt;enumeration value="less"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QueryParameterOperatorType")
@XmlEnum
public enum QueryParameterOperatorType {


    /**
     * 
     *             The Query Parameter Operator "equal to" test attribute.
     *           
     * 
     */
    @XmlEnumValue("equal")
    EQUAL("equal"),

    /**
     * 
     *             The Query Parameter Operator "not equal to" test attribute.
     *           
     * 
     */
    @XmlEnumValue("notEqual")
    NOT_EQUAL("notEqual"),

    /**
     * 
     *             The Query Parameter Operator "greater than" test attribute.
     *           
     * 
     */
    @XmlEnumValue("greater")
    GREATER("greater"),

    /**
     * 
     *             The Query Parameter Operator "less than" test attribute.
     *           
     * 
     */
    @XmlEnumValue("less")
    LESS("less");
    private final String value;

    QueryParameterOperatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QueryParameterOperatorType fromValue(String v) {
        for (QueryParameterOperatorType c: QueryParameterOperatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
