//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 10:49:01 AM CET 
//


package org.imf.oplexecutor.fims.bms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScanningFormatType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScanningFormatType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="interlaced"/>
 *     &lt;enumeration value="progressive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScanningFormatType")
@XmlEnum
public enum ScanningFormatType {


    /**
     * Scanning Format Type Interlaced value.
     * 
     */
    @XmlEnumValue("interlaced")
    INTERLACED("interlaced"),

    /**
     * Scanning Format Type Progressive value.
     * 
     */
    @XmlEnumValue("progressive")
    PROGRESSIVE("progressive");
    private final String value;

    ScanningFormatType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScanningFormatType fromValue(String v) {
        for (ScanningFormatType c: ScanningFormatType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
